compute-resource:
  refresh: 10
  files:
    protocol: sftp
    location: cartesius.surfsara.nl
    path: /home/$CERISE_USERNAME/.cerise

  jobs:
    protocol: ssh
    location: cartesius.surfsara.nl
    scheduler: slurm
    cwl-runner: $CERISE_API_FILES/cerise/cwltiny.py
    slots-per-node: 4
