compute-resource:
  refresh: 10
  files:
    protocol: sftp
    location: cartesius.surfsara.nl
    path: /home/$CERISE_USERNAME/.cerise

  jobs:
    protocol: ssh
    location: cartesius.surfsara.nl
    scheduler: slurm
    cwl-runner:  $CERISE_API_FILES/mdstudio/github/cerise-mdstudio-cartesius/mdstudio/wrappers/call_cwltiny.sh
    slots-per-node: 4
